
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.LinkedList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


public class MenuAdministradorReportes extends javax.swing.JFrame {
    
    LinkedList<Orden>ordenes;

    public MenuAdministradorReportes(LinkedList<Orden>ordenes) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.ordenes = ordenes;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        uiBGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        uiTReportes = new javax.swing.JTextArea();
        uiBCargar = new javax.swing.JButton();
        btnPrioridad = new javax.swing.JButton();

        setTitle("Menu Administrador Reportes");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Reporte de Ventas");

        uiBGuardar.setBackground(new java.awt.Color(255, 215, 0));
        uiBGuardar.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        uiBGuardar.setText("Guardar Ordenes");
        uiBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiBGuardarActionPerformed(evt);
            }
        });

        uiTReportes.setColumns(20);
        uiTReportes.setRows(5);
        jScrollPane1.setViewportView(uiTReportes);

        uiBCargar.setBackground(new java.awt.Color(255, 215, 0));
        uiBCargar.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        uiBCargar.setText("Cargar Ordenes");
        uiBCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiBCargarActionPerformed(evt);
            }
        });

        btnPrioridad.setBackground(new java.awt.Color(255, 215, 0));
        btnPrioridad.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        btnPrioridad.setText("Orden Prioritario");
        btnPrioridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrioridadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(99, 99, 99)
                                .addComponent(uiBGuardar)
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(uiBCargar)
                                .addGap(38, 38, 38)
                                .addComponent(btnPrioridad))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(uiBGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uiBCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uiBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiBGuardarActionPerformed

         JFileChooser WinGuardar = new JFileChooser();
        int decisión = WinGuardar.showSaveDialog(null);
        if (decisión == JFileChooser.APPROVE_OPTION) {
            try {
                File archivo = WinGuardar.getSelectedFile();
                FileOutputStream fos = new FileOutputStream(archivo);
                ObjectOutputStream oos = new ObjectOutputStream(fos);

                oos.writeObject(PaginaPrincipal.ordenes);
                oos.close();
            } catch (IOException e) {
                System.err.println(e);
            }
        }
    }//GEN-LAST:event_uiBGuardarActionPerformed

    private void uiBCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiBCargarActionPerformed
        JFileChooser WinCargar = new JFileChooser();
        int decisión = WinCargar.showSaveDialog(null);
        if (decisión == JFileChooser.APPROVE_OPTION) {
            try {
                File archivo = WinCargar.getSelectedFile();
                FileInputStream fos = new FileInputStream(archivo);
                ObjectInputStream oos = new ObjectInputStream(fos);
                LinkedList<Orden> cargar = (LinkedList<Orden>) oos.readObject();
                oos.close();
                String datos = "";
                int totalganado = 0;
                int cantidad = cargar.size();
                for (Orden ventas : cargar) {
                   
                  datos= "***********************************************\n" + datos + ventas.toString() + "\n***********************************************\n";
                  totalganado = totalganado + ventas.monto; 
                     
                }
                datos = datos + "\n Total Ganado en el día: ₡" + totalganado;
                uiTReportes.append(datos);
            } catch (IOException | ClassNotFoundException e) {
                System.err.println(e);
            }
        }
    }//GEN-LAST:event_uiBCargarActionPerformed

    private void btnPrioridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrioridadActionPerformed
        Orden prioritaria = new Orden();
        for (Orden o : ordenes){
            if (o.monto > prioritaria.monto){
                prioritaria = o;
            }
        }
        JOptionPane.showMessageDialog(null, prioritaria.toString());
    }//GEN-LAST:event_btnPrioridadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrioridad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton uiBCargar;
    private javax.swing.JButton uiBGuardar;
    private javax.swing.JTextArea uiTReportes;
    // End of variables declaration//GEN-END:variables
}
