
import java.util.LinkedList;
import javax.swing.*;
import sun.misc.PerformanceLogger;

public class PaginaPrincipal extends javax.swing.JFrame {
    public static LinkedList<Orden> ordenes = new LinkedList();
    private int pizzaPersonal = 2500;
    private int pizzaPequeña = 4000;
    private int pizzaMediana = 6000;
    private int pizzaGrande = 8000;
    private int pizzaExtraGrande = 10000;
    private int total = 0;
    private String Clasica;
    private String jamonhongos;
    private String peperoni;
    private String suprema;
    private String triplequeso;
    private String vegetariana;
    //************************* Atributos para Clase orden
    private String nombre = "";
    private String cedula = "";
    private String correo= "";
    private String sabor = "";
    private String tamaño = "";
    private int cantidad = 0;
    private String tipo = "";

    public PaginaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);

    }
    
      private void LimpiarCampos(){
        uiTNombre.setText("");
        uiTCedula.setText("");
        uiTNumeroTelefono.setText("");
        uiTCorreo.setText("");
        uiTADireccion.setText("");
        uiTCantidad.setText("");
        if(jRadioButton2.isSelected()){
            jRadioButton2.setSelected(false);
        }else if(jRadioButton1.isSelected()){
            jRadioButton1.setSelected(false);
        }else if(jRadioButton3.isSelected()){
            jRadioButton3.setSelected(false);
        }else if(jRadioButton4.isSelected()){
            jRadioButton4.setSelected(false);
        }
        if(uiCFacturaSi.isSelected()){
            uiCFacturaSi.setSelected(false);
        }else if(uiCFacturaNo.isSelected()){
            uiCFacturaNo.setSelected(false);
        }
   }
      
      private boolean comprobacionNumerica(String text){
          try {
              int num = Integer.parseInt(text);
              return true;
          } catch (NumberFormatException e){
              return false;
          }
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        uiCSeleccion = new javax.swing.JComboBox<>();
        uiBFinalizarComprar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        uiBMenuAdministrador1 = new javax.swing.JButton();
        uiTNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        uiTCedula = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        uiTADireccion = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        uiTNumeroTelefono = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        uiTCorreo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        uiCFacturaNo = new javax.swing.JRadioButton();
        uiCFacturaSi = new javax.swing.JRadioButton();
        uiCTamaño = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        uiTCantidad = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        uiTAFactura = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        jLabel6.setFont(new java.awt.Font("Myanmar Text", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Elija el Sabor de la Pizza:");

        jLabel8.setFont(new java.awt.Font("Myanmar Text", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Dirección Exacta: ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        uiCSeleccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clásica", "Jamón y Hongos", "Pepperoni", "Suprema", "Triple Queso", "Vegetariana" }));
        uiCSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiCSeleccionActionPerformed(evt);
            }
        });

        uiBFinalizarComprar.setBackground(new java.awt.Color(255, 215, 0));
        uiBFinalizarComprar.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        uiBFinalizarComprar.setText("Finalizar Compra");
        uiBFinalizarComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiBFinalizarComprarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Myanmar Text", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre Completo: ");

        uiBMenuAdministrador1.setBackground(new java.awt.Color(255, 215, 0));
        uiBMenuAdministrador1.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        uiBMenuAdministrador1.setText("Menú Administrador");
        uiBMenuAdministrador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiBMenuAdministrador1ActionPerformed(evt);
            }
        });

        uiTNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiTNombreActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Myanmar Text", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cedula de Identidad: ");

        uiTCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiTCedulaActionPerformed(evt);
            }
        });

        uiTADireccion.setColumns(20);
        uiTADireccion.setRows(5);
        jScrollPane1.setViewportView(uiTADireccion);

        jLabel5.setFont(new java.awt.Font("Myanmar Text", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Adicionales:");

        jLabel7.setFont(new java.awt.Font("Myanmar Text", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cantidad:");

        jLabel9.setFont(new java.awt.Font("Myanmar Text", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Numero Telefónico:");

        uiTNumeroTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiTNumeroTelefonoActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N
        jLabel10.setText("jLabel10");

        jLabel11.setFont(new java.awt.Font("Myanmar Text", 3, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Dirección Exacta: ");

        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Queso");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Hongos");

        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("Jamón");

        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("Pepperoni");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Myanmar Text", 3, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Correo Electrónico:");

        uiTCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiTCorreoActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Myanmar Text", 3, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Factura Electrónica:");

        buttonGroup1.add(uiCFacturaNo);
        uiCFacturaNo.setForeground(new java.awt.Color(255, 255, 255));
        uiCFacturaNo.setText("No");
        uiCFacturaNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiCFacturaNoActionPerformed(evt);
            }
        });

        buttonGroup1.add(uiCFacturaSi);
        uiCFacturaSi.setForeground(new java.awt.Color(255, 255, 255));
        uiCFacturaSi.setText("Sí");
        uiCFacturaSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiCFacturaSiActionPerformed(evt);
            }
        });

        uiCTamaño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Personal", "Pequeña", "Mediana", "Grande", "Extragrande", " " }));
        uiCTamaño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiCTamañoActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Myanmar Text", 3, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Sabor de la Pizza:");

        jLabel15.setFont(new java.awt.Font("Myanmar Text", 3, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Tamaño: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11))
                                .addComponent(jLabel14))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(uiTNumeroTelefono, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(uiTNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(uiTCedula, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(uiTCorreo, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(uiCFacturaSi)
                                .addGap(18, 18, 18)
                                .addComponent(uiCFacturaNo)))
                        .addContainerGap(143, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel5)
                        .addGap(83, 83, 83)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton3))
                            .addComponent(uiCSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(uiCTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jRadioButton4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(uiTCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(uiBFinalizarComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(281, 281, 281))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(611, Short.MAX_VALUE)
                    .addComponent(uiBMenuAdministrador1)
                    .addGap(20, 20, 20)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(uiTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(uiTCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(uiTNumeroTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addGap(6, 6, 6))
                    .addComponent(uiTCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(uiCFacturaNo)
                    .addComponent(uiCFacturaSi))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(uiCSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(uiCTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uiTCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(uiBFinalizarComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(uiBMenuAdministrador1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(615, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Orden", jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        uiTAFactura.setColumns(20);
        uiTAFactura.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        uiTAFactura.setRows(5);
        jScrollPane2.setViewportView(uiTAFactura);

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Factura", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uiBFinalizarComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiBFinalizarComprarActionPerformed
        
        nombre = uiTNombre.getText();
        cedula = uiTCedula.getText();
        correo = uiTCorreo.getText();
        
        perfomance: {
        boolean bCedula = comprobacionNumerica(uiTCedula.getText());
        boolean bTelefono = comprobacionNumerica(uiTNumeroTelefono.getText());
        if (bTelefono && bCedula) {
            JOptionPane.showMessageDialog(null, "Gracias por su compra! \n Proceda a ver su factura en la pestaña: Factura");
        }else{
            JOptionPane.showMessageDialog(null, "Datos incorrectos, verifique el numero telefonico o el numero de cedula");
            break perfomance;
        }
        
        
        uiTAFactura.append("                    PIZZA FIDE \nDetalle de Compra: \nNombre:" + uiTNombre.getText() + "\n" + "celular: " + uiTNumeroTelefono.getText() + "\n");

        if (uiCSeleccion.getSelectedItem().equals("Clásica")) {
            sabor = "Clasica";
            uiTAFactura.append("Sabor de pizza:Clásica \n");
        } else if (uiCSeleccion.getSelectedItem().equals("Jamón y Hongos")) {
            sabor = "Jamón y Hongos";
            uiTAFactura.append("Sabor de pizza:Jamón y Hongos \n");
        } else if (uiCSeleccion.getSelectedItem().equals("Pepperoni")) {
            sabor = "Jamón y Hongos";
            uiTAFactura.append("Sabor de pizza:Pepperoni \n");
        } else if (uiCSeleccion.getSelectedItem().equals("Suprema")) {
            sabor = "Suprema";
            uiTAFactura.append("Sabor de pizza:Suprema \n");
        } else if (uiCSeleccion.getSelectedItem().equals("Triple Queso")) {
            sabor = "Triple Queso";
            uiTAFactura.append("Sabor de pizza:Triple Queso \n");

        } else if (uiCSeleccion.getSelectedItem().equals("Vegetariana")) {
            sabor = "Vegetariana";
            uiTAFactura.append("Sabor de pizza:Vegetariana \n");

        }
        uiTAFactura.append("Cantidad: " + uiTCantidad.getText() + "\n");
        cantidad = Integer.parseInt(uiTCantidad.getText());
        if (jRadioButton2.isSelected()) {
            String Hongos = jRadioButton2.getText();
            uiTAFactura.append("Adicionales: Hongos \n");

        } else if (jRadioButton3.isSelected()) {
            String Jamón = jRadioButton3.getText();
            uiTAFactura.append("Adicionales: Jamón \n");

        } else if (jRadioButton4.isSelected()) {
            String Pepperoni = jRadioButton4.getText();
            uiTAFactura.append("Adicionales: Pepperoni \n");

        } else if (jRadioButton1.isSelected()) {
            String Queso = jRadioButton1.getText();
            uiTAFactura.append("Adicionales: Queso \n");

        }

        if (uiCTamaño.getSelectedItem().equals("Personal")) {
            tamaño = "Personal";
            total = pizzaPersonal * Integer.parseInt(uiTCantidad.getText());
            uiTAFactura.append("Tamaño de Pizza:personal \nTotal: ₡" + total + "\n");
            uiTAFactura.append("---------------------------------------------------------------------------\n");
        } else if (uiCTamaño.getSelectedItem().equals("Pequeña")) {
            tamaño = "Pequeña";
            total = pizzaPequeña * Integer.parseInt(uiTCantidad.getText());
            uiTAFactura.append("Tamaño de Pizza:Pequeña \nTotal: ₡" + total + "\n");
            {
                uiTAFactura.append("---------------------------------------------------------------------------\n");
            }
        } else if (uiCTamaño.getSelectedItem().equals("Mediana")) {
            tamaño = "Mediana";
            total = pizzaMediana * Integer.parseInt(uiTCantidad.getText());
            uiTAFactura.append("Tamaño de Pizza:Mediana \nTotal: ₡" + total + "\n");
            {
                uiTAFactura.append("---------------------------------------------------------------------------\n");
            }
        } else if (uiCTamaño.getSelectedItem().equals("Grande")) {
            tamaño = "Grande";
            total = pizzaGrande * Integer.parseInt(uiTCantidad.getText());
            uiTAFactura.append("Tamaño de Pizza:Grande \nTotal: ₡" + total + "\n");
            {
                uiTAFactura.append("---------------------------------------------------------------------------\n");
            }
        } else if (uiCTamaño.getSelectedItem().equals("Extragrande")) {
            tamaño = "ExtraGrande";
            total = pizzaExtraGrande * Integer.parseInt(uiTCantidad.getText());
            uiTAFactura.append("Tamaño de Pizza:ExtraGrande \nTotal: ₡" + total + "\n");
            {
                uiTAFactura.append("---------------------------------------------------------------------------\n");

            }
    }//GEN-LAST:event_uiBFinalizarComprarActionPerformed
    Orden orden = new Orden(nombre, cedula, correo, sabor, tamaño, cantidad, total);
    ordenes.add(orden);
    String datos = "";
    LimpiarCampos();
        }
    
    
    
    }
    private void uiBMenuAdministrador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiBMenuAdministrador1ActionPerformed
        MenuAdministrador m = new MenuAdministrador(ordenes);
        m.setVisible(true);

    }//GEN-LAST:event_uiBMenuAdministrador1ActionPerformed

    private void uiTNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiTNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uiTNombreActionPerformed

    private void uiTCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiTCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uiTCedulaActionPerformed

    private void uiTNumeroTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiTNumeroTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uiTNumeroTelefonoActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void uiTCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiTCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uiTCorreoActionPerformed

    private void uiCFacturaNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiCFacturaNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uiCFacturaNoActionPerformed

    private void uiCFacturaSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiCFacturaSiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uiCFacturaSiActionPerformed

    private void uiCTamañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiCTamañoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uiCTamañoActionPerformed

    private void uiCSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiCSeleccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uiCSeleccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton uiBFinalizarComprar;
    private javax.swing.JButton uiBMenuAdministrador1;
    private javax.swing.JRadioButton uiCFacturaNo;
    private javax.swing.JRadioButton uiCFacturaSi;
    private javax.swing.JComboBox<String> uiCSeleccion;
    private javax.swing.JComboBox<String> uiCTamaño;
    private javax.swing.JTextArea uiTADireccion;
    private javax.swing.JTextArea uiTAFactura;
    private javax.swing.JTextField uiTCantidad;
    private javax.swing.JTextField uiTCedula;
    private javax.swing.JTextField uiTCorreo;
    private javax.swing.JTextField uiTNombre;
    private javax.swing.JTextField uiTNumeroTelefono;
    // End of variables declaration//GEN-END:variables
}
